// <auto-generated />
using Desafio_Balta_IBGE.Infra.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Desafio_Balta_IBGE.Infra.Migrations
{
    [DbContext(typeof(IbgeContext))]
    partial class IbgeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "7.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Desafio_Balta_IBGE.Domain.Models.Ibge", b =>
                {
                    b.Property<string>("IbgeId")
                        .HasColumnType("char(7)")
                        .HasColumnName("IbgeId");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("varchar(80)")
                        .HasColumnName("City");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("char(2)")
                        .HasColumnName("State");

                    b.HasKey("IbgeId");

                    b.ToTable("Ibge", (string)null);
                });
#pragma warning restore 612, 618
        }
    }
}
